#!/bin/sh -e

first="-p 5433 first"
second="-p 5434 second"
psql='psql --no-psqlrc'

$psql $first -c "
begin;
insert into debits (amt) values (49);
commit;
begin;
update debits set amt=50 where amt=49;
prepare transaction 't_002';
"

$psql $second -c "
begin;
insert into credits (amt) values (49);
commit;
begin;
update credits set amt=50 where amt=49;
prepare transaction 't_002';
"
